//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TresureHunt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TresureHunt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;First Name&quot;,&quot;Last Name&quot;
        ///&quot;Martin&quot;,&quot;Parker&quot;
        ///&quot;Lucia&quot;,&quot;Bailey&quot;
        ///&quot;Catherine&quot;,&quot;Wilson&quot;
        ///&quot;Daryl&quot;,&quot;Craig&quot;
        ///&quot;Fiona&quot;,&quot;Lloyd&quot;
        ///&quot;Gianna&quot;,&quot;Parker&quot;
        ///&quot;Carlos&quot;,&quot;Chapman&quot;
        ///&quot;Adrianna&quot;,&quot;Morgan&quot;
        ///&quot;Amy&quot;,&quot;Campbell&quot;
        ///&quot;Daisy&quot;,&quot;Fowler&quot;
        ///&quot;Florrie&quot;,&quot;Martin&quot;
        ///&quot;Myra&quot;,&quot;Robinson&quot;
        ///&quot;Julian&quot;,&quot;Alexander&quot;
        ///&quot;Chloe&quot;,&quot;Mitchell&quot;
        ///&quot;Alexia&quot;,&quot;Barrett&quot;
        ///&quot;Thomas&quot;,&quot;Robinson&quot;
        ///&quot;Camila&quot;,&quot;Grant&quot;
        ///&quot;George&quot;,&quot;Williams&quot;
        ///&quot;Darcy&quot;,&quot;Clark&quot;
        ///&quot;Steven&quot;,&quot;West&quot;
        ///&quot;Anna&quot;,&quot;Walker&quot;
        ///&quot;Ada&quot;,&quot;Grant&quot;
        ///&quot;Roman&quot;,&quot;Williams&quot;
        ///&quot;Natalie&quot;,&quot;Douglas&quot;
        ///&quot;Garry&quot;,&quot;Moore&quot;...
        /// </summary>
        internal static string RandomNames {
            get {
                return ResourceManager.GetString("RandomNames", resourceCulture);
            }
        }
    }
}
